Repository open-policy-agent/opa, pull requests merged in 2022-08, with the labels that each got.

#4956 topdown/reachable: Fix missing operand type checks.
  test/cases/testdata/reachable/test-reachable-0326.yaml
  test/cases/testdata/reachable/test-reachable-0328.yaml
  test/cases/testdata/reachable/test-reachable-paths-0422.yaml
  topdown/reachable.go
  wasm/src/graphs.c
  wasm/tests/test.c
Labels: builtins

#4971 Docs: GraphQL update serving port and make bundles folder
  docs/content/graphql-api-authorization.md
Labels: docs

#4992 docs: Update release procedure with branch/fork workflow.
  docs/devel/RELEASE.md
Labels: docs

#4980 builtins: Speed up set unions
  topdown/sets.go
  topdown/sets_bench_test.go
  topdown/sets_test.go
Labels: builtins

#5011 topdown/units_parse: Avoid extra decimal places for integers.
  test/cases/testdata/units/test-units-precision.yaml
  topdown/parse_units.go
Labels: builtins

#4999 Set Insertion Rework
  ast/term.go
  ast/term_bench_test.go
  ast/term_test.go
Labels: optimization, performance

#5033 test/e2e/certrefresh: Add file.Sync() to eliminate slow write failures.
  test/e2e/certrefresh/certrefresh_test.go
Labels: investigating
