Repository open-policy-agent/opa, pull requests merged in 2023-10, with the labels that each got.

#6239 This change adds support to configurable prometheus buckets
  config/config.go
  config/config_test.go
  docs/content/configuration.md
  internal/prometheus/prometheus.go
  internal/prometheus/prometheus_go1.19_test.go
  internal/prometheus/prometheus_test.go
  plugins/server/metrics/config.go
  plugins/server/metrics/config_test.go
  runtime/runtime.go
  runtime/runtime_test.go
  server/server_test.go
Labels: waiting-for-response

#6299 Drop EXPERIMENTAL status of reported prom metrics
  docs/content/monitoring.md
Labels: pre1.0

#6300 server: Remove partial query parameter
  runtime/logging.go
  server/server.go
  server/server_test.go
  server/types/types.go
Labels: pre1.0

#6309 Bind OPA server to localhost interface by default
  cmd/run.go
  cmd/run_test.go
  docs/content/_index.md
  docs/content/deployments.md
  docs/content/security.md
  runtime/runtime.go
  runtime/runtime_test.go
Labels: 1.0
