Repository open-policy-agent/opa, pull requests merged in 2023-01, with the labels that each got.

#5526 ast/parser: Detect function rule head + contains keyword.
  ast/check.go
  ast/compile_test.go
  ast/parser.go
  ast/parser_test.go
Labels: bug

#5557 build: bump golang 1.19.4 -> 1.19.5
  .go-version
  topdown/http_test.go
Labels: waiting-for-response

#5522 fix prefix error in `opa inspect` for bundle from root
  build/binary-smoke-test.sh
  bundle/file.go
  test/cli/smoke/.manifest
Labels: waiting-for-response

#5614 docs/graphql: non-nullable id argument and typo fix.
  docs/content/graphql-api-authorization.md
Labels: docs
